[options]
db_host = False
db_port = False
db_user = False
db_password = False
addons_path = /odoo/addons,/odoo/customaddons
http_port = 8019
admin_passwd = $pbkdf2-sha512$600000$j5HyntP631tLSQlhDAHg3A$M5aYq6Cx8mTKoNQsIh5/ExNbRUvqAgx7R14J0bivjvLVAUu8S0v101EvqJfpTqa3zuwIzOTCp//3lVlTCanIyw

